"""Aggiunti campi per giorni di ferie

Revision ID: 26b7f8b952ae
Revises: 
Create Date: 2024-12-02 11:49:25.162756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b7f8b952ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_holiday_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remaining_holiday_days', sa.Integer(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('remaining_holiday_days')
        batch_op.drop_column('annual_holiday_days')

    # ### end Alembic commands ###
