"""Add indexes on bookings

Revision ID: 37b7d622b959
Revises: 5a25b0f424da
Create Date: 2024-12-10 16:00:11.139370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b7d622b959'
down_revision = '5a25b0f424da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_is_rejected'), ['is_rejected'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_is_validated'), ['is_validated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_is_validated'))
        batch_op.drop_index(batch_op.f('ix_booking_is_rejected'))

    # ### end Alembic commands ###
