"""Add annual_credits to users

Revision ID: 5a25b0f424da
Revises: f5b4d778ccd2
Create Date: 2024-12-06 17:01:39.930915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a25b0f424da'
down_revision = 'f5b4d778ccd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_credits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('annual_credits')

    # ### end Alembic commands ###
