"""Aggiunto campo is_rejected a Booking

Revision ID: f5b4d778ccd2
Revises: 4cfea795f186
Create Date: 2024-12-03 10:38:01.693181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b4d778ccd2'
down_revision = '4cfea795f186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rejected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('is_rejected')

    # ### end Alembic commands ###
